language: python

git:
  depth: false

python:
  - "3.5"
  - "3.6"

jobs:
  include:
    # special deploy stage for tag builds ONLY
    - stage: deploy
      if: tag IS present
      script: skip
      after_script: skip
      deploy:
        provider: pypi
        user: "${PYPI_USERNAME}"
        password: "${PYPI_PASSWORD}"
        on:
          tags: true

before_install:
  - pip install --upgrade pip  # some TravisCI images have outdated pip

install:
  - pip install .[dev]

script:
  - scripts/travisci/check_precommit.sh
  - flake8 src
  - flake8 --exclude=src,docs --extend-ignore=D
  - pushd docs && make html && popd

notifications:
  email: false
